Feature/customize clubhouse story title and body
singingwolfboy/create-linked-clubhouse-story pull request #10
Opened 2020-09-29 05:28 UTC by jdcargile

@singingwolfboy, this PR has a feature that includes the ability for users of this GitHub Action to customize the title and body of the created Clubhouse story using the same custom comment template you're using for the PR comments. If neither `clubhouse-story-title-template` nor `clubhouse-story-body-template` is populated, it simple defaults to the `payload.pull_request.title` and `payload.pull_request.body` as requested.

2020-10-02 10:16 UTC, singingwolfboy requested changes
I added a few comments for suggested changes, and this pull request needs some automated tests, as well. But I really like where this is going, and I think it will be a useful feature and ready to merge soon! 🎉

2020-10-02 10:16 UTC, singingwolfboy commented on src/util.ts
> +  storyBody: string
Rather than making this function accept arguments for `storyTitle` and `storyBody`, could you please construct those values inside the `createClubhouseStory` function? That keeps the `opened.ts` file clearer, and allows for easier testing, as well.

2020-10-02 10:16 UTC, singingwolfboy commented on src/opened.ts
> +    payload,
Rather than passing the `payload` object to the Mustache environment, I think it's clearer to pass the pull request object, like this:
```
{ pullRequest: payload.pull_request }
```

I doubt that template authors will need any other information from the payload. I'm undecided about `pullRequest` vs `pull_request`, but I feel like the former is more Javascripty, so that's why I'm leaning towards it.

2020-10-02 10:16 UTC, singingwolfboy commented on README.md
> +## Customizing the Clubhouse Story Title and Body
This is great! Thank you for adding this documentation 😄

2020-10-02 10:16 UTC, singingwolfboy commented on README.md
> +- uses: singingwolfboy/create-linked-clubhouse-story@v1.7
Please leave this at `v1.5` for now. I'll update all the version references in this file when I release a new version.

2020-10-02 14:35 UTC, jdcargile commented on src/util.ts
> +  storyBody: string
@singingwolfboy, I debated this too thinking `pull_request` would have everything I would want to use, but then when I tried to do what I was doing before of concatenating the `repo.name` to the Clubhouse story, it was missing in the `payload.pull_request` object.

2020-10-02 14:36 UTC, jdcargile commented on src/opened.ts
> +    payload,
@singingwolfboy, I debated this too thinking `pull_request` would have everything I would want to use, but then when I tried to do what I was doing before of concatenating the `repo.name` to the Clubhouse story, it was missing in the `payload.pull_request` object.

2020-10-02 14:36 UTC, jdcargile commented on src/util.ts
> +  storyBody: string
Sure, no problem!

2020-10-02 14:37 UTC, jdcargile commented on README.md
> +## Customizing the Clubhouse Story Title and Body
👍

2020-10-02 14:37 UTC, jdcargile commented on README.md
> +- uses: singingwolfboy/create-linked-clubhouse-story@v1.7
Sure! No problem!

2020-10-02 14:38 UTC, singingwolfboy commented on src/opened.ts
> +    payload,
Oh, I didn't consider that! Alright, then I guess the `payload` object is the way to go.

2020-10-02 20:00 UTC, jdcargile commented on src/util.ts
> +  storyBody: string
@singingwolfboy, the `title` and `description` for the story are now in the `createClubhouseStory` method.

2020-10-02 20:01 UTC, jdcargile commented on src/opened.ts
> +    payload,
Thank you. Leaving `payload` whole as the passed attribute.

2020-10-02 20:01 UTC, jdcargile commented on README.md
> +- uses: singingwolfboy/create-linked-clubhouse-story@v1.7
Done.

2020-10-02 20:02 UTC, jdcargile commented
@singingwolfboy, what did you have envisioned for the automated tests for the `createClubhouseStory` method. There is a fair amount of logic in that method that might need to be broken out to do the testing I see elsewhere in the project. Please provide a little more guidance on this.

2020-10-03 11:38 UTC, singingwolfboy commented
Thanks for all your work on this! I think I'll just merge this, and write some tests myself.

2020-10-03 11:39 UTC, merged

2020-10-03 13:00 UTC, singingwolfboy commented
Here are the tests I put together: https://github.com/singingwolfboy/create-linked-clubhouse-story/commit/5130a7fbbc4bca023d4c4ae30932bfac5902be74

Getting everything to work right with `nock` was harder than I thought it would be!